# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: ./sysctl.id
title: ./sysctl.id
email: awcodify@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Performance engineering really help us to handle expected or even
  unexpected amount of traffic without any issue.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sysctl.id" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  awcodify
github: [metadata]

# Build settings
remote_theme: awcodify/long-haul
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# long-haul theme config
header: normal
url: https://sysctl.id
permalink: /:title/
sass:
    style: compressed
markdown: kramdown
highlighter: rouge

paginate: 5
paginate_path: "/page/:num/"

navigation:
    - title: Home
      url: /
    - title: About
      url: /about
    - title: English
      url: /english
    - title: Indonesia
      url: /bahasa-indonesia
    - title: Tags
      url: /tags
    - title: Contact
      url: /contact

social:
    github: awcodify
    email: awcodify@gmail.com

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

header_pages:
  - tags.html
  - about.md
  - contact.md

# style: terminal # dark (default), light or hacker
# listen_for_clients_preferred_style: true # false (default) or true
google_analytics: G-MLFFR89WJX
excerpt_separator: <!--more-->

disqus:
    shortname: sysctl-id